/**
 * ★ AUTO-GENERATED by `npm run enums:sync` — DO NOT EDIT（架构 §10.11）
 * 来源：prisma/schema.prisma（30 个 enum）。
 * 修改枚举请改 schema 后重新运行 `npm run enums:sync`。
 */
import { z } from 'zod'

export type Role =
  | 'USER'
  | 'TEACHER'
  | 'ADMIN'

export const ROLE_VALUES = [
  'USER',
  'TEACHER',
  'ADMIN',
] as const

export const roleSchema = z.enum(ROLE_VALUES)

export type UserStatus =
  | 'ACTIVE'
  | 'DISABLED'
  | 'PENDING'
  | 'DELETED'

export const USER_STATUS_VALUES = [
  'ACTIVE',
  'DISABLED',
  'PENDING',
  'DELETED',
] as const

export const userStatusSchema = z.enum(USER_STATUS_VALUES)

export type CEFRLevel =
  | 'A1'
  | 'A2'
  | 'B1'
  | 'B2'
  | 'C1'
  | 'C2'

export const CEFRLEVEL_VALUES = [
  'A1',
  'A2',
  'B1',
  'B2',
  'C1',
  'C2',
] as const

export const cEFRLevelSchema = z.enum(CEFRLEVEL_VALUES)

export type MasteryStage =
  | 'NEW'
  | 'STRANGER'
  | 'LEARNING'
  | 'FAMILIAR'
  | 'PROFICIENT'
  | 'MASTERED'

export const MASTERY_STAGE_VALUES = [
  'NEW',
  'STRANGER',
  'LEARNING',
  'FAMILIAR',
  'PROFICIENT',
  'MASTERED',
] as const

export const masteryStageSchema = z.enum(MASTERY_STAGE_VALUES)

export type GoalType =
  | 'CET4'
  | 'CET6'
  | 'KAOYAN'
  | 'IELTS'
  | 'TOEFL'
  | 'DAILY'
  | 'BUSINESS'
  | 'INTEREST'
  | 'ABROAD'

export const GOAL_TYPE_VALUES = [
  'CET4',
  'CET6',
  'KAOYAN',
  'IELTS',
  'TOEFL',
  'DAILY',
  'BUSINESS',
  'INTEREST',
  'ABROAD',
] as const

export const goalTypeSchema = z.enum(GOAL_TYPE_VALUES)

export type GoalStatus =
  | 'ACTIVE'
  | 'ACHIEVED'
  | 'ABANDONED'

export const GOAL_STATUS_VALUES = [
  'ACTIVE',
  'ACHIEVED',
  'ABANDONED',
] as const

export const goalStatusSchema = z.enum(GOAL_STATUS_VALUES)

/** CET4/CET6/考研/雅思/托福 + 模拟卷/自定义/水平测试 */
export type ExamType =
  | 'CET4'
  | 'CET6'
  | 'KAOYAN'
  | 'IELTS'
  | 'TOEFL'
  | 'MOCK'
  | 'CUSTOM'
  | 'PLACEMENT'

export const EXAM_TYPE_VALUES = [
  'CET4',
  'CET6',
  'KAOYAN',
  'IELTS',
  'TOEFL',
  'MOCK',
  'CUSTOM',
  'PLACEMENT',
] as const

export const examTypeSchema = z.enum(EXAM_TYPE_VALUES)

export type Difficulty =
  | 'EASY'
  | 'MEDIUM'
  | 'HARD'

export const DIFFICULTY_VALUES = [
  'EASY',
  'MEDIUM',
  'HARD',
] as const

export const difficultySchema = z.enum(DIFFICULTY_VALUES)

export type QuestionType =
  | 'SINGLE_CHOICE'
  | 'MULTI_CHOICE'
  | 'TRUE_FALSE'
  | 'FILL_BLANK'
  | 'CLOZE'
  | 'MATCHING'
  | 'SHORT_ANSWER'
  | 'ESSAY'
  | 'TRANSLATION'
  | 'DICTATION'
  | 'RETELL'
  | 'SUMMARY'

export const QUESTION_TYPE_VALUES = [
  'SINGLE_CHOICE',
  'MULTI_CHOICE',
  'TRUE_FALSE',
  'FILL_BLANK',
  'CLOZE',
  'MATCHING',
  'SHORT_ANSWER',
  'ESSAY',
  'TRANSLATION',
  'DICTATION',
  'RETELL',
  'SUMMARY',
] as const

export const questionTypeSchema = z.enum(QUESTION_TYPE_VALUES)

export type ExamSection =
  | 'LISTENING'
  | 'READING'
  | 'WRITING'
  | 'TRANSLATION'

export const EXAM_SECTION_VALUES = [
  'LISTENING',
  'READING',
  'WRITING',
  'TRANSLATION',
] as const

export const examSectionSchema = z.enum(EXAM_SECTION_VALUES)

export type AttemptStatus =
  | 'IN_PROGRESS'
  | 'SUBMITTED'
  | 'GRADING'
  | 'GRADED'
  | 'ABANDONED'
  | 'EXPIRED'

export const ATTEMPT_STATUS_VALUES = [
  'IN_PROGRESS',
  'SUBMITTED',
  'GRADING',
  'GRADED',
  'ABANDONED',
  'EXPIRED',
] as const

export const attemptStatusSchema = z.enum(ATTEMPT_STATUS_VALUES)

export type PublishStatus =
  | 'DRAFT'
  | 'PENDING_REVIEW'
  | 'PUBLISHED'
  | 'OFFLINE'
  | 'REJECTED'

export const PUBLISH_STATUS_VALUES = [
  'DRAFT',
  'PENDING_REVIEW',
  'PUBLISHED',
  'OFFLINE',
  'REJECTED',
] as const

export const publishStatusSchema = z.enum(PUBLISH_STATUS_VALUES)

export type PlanSource =
  | 'AI'
  | 'RULE'
  | 'MANUAL'

export const PLAN_SOURCE_VALUES = [
  'AI',
  'RULE',
  'MANUAL',
] as const

export const planSourceSchema = z.enum(PLAN_SOURCE_VALUES)

export type PlanStatus =
  | 'ACTIVE'
  | 'PAUSED'
  | 'COMPLETED'
  | 'ARCHIVED'

export const PLAN_STATUS_VALUES = [
  'ACTIVE',
  'PAUSED',
  'COMPLETED',
  'ARCHIVED',
] as const

export const planStatusSchema = z.enum(PLAN_STATUS_VALUES)

export type TaskType =
  | 'VOCAB'
  | 'REVIEW'
  | 'LISTENING'
  | 'READING'
  | 'WRITING'
  | 'SPEAKING'
  | 'GRAMMAR'
  | 'TRANSLATION'
  | 'EXAM'

export const TASK_TYPE_VALUES = [
  'VOCAB',
  'REVIEW',
  'LISTENING',
  'READING',
  'WRITING',
  'SPEAKING',
  'GRAMMAR',
  'TRANSLATION',
  'EXAM',
] as const

export const taskTypeSchema = z.enum(TASK_TYPE_VALUES)

export type TaskStatus =
  | 'PENDING'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'SKIPPED'
  | 'EXPIRED'

export const TASK_STATUS_VALUES = [
  'PENDING',
  'IN_PROGRESS',
  'COMPLETED',
  'SKIPPED',
  'EXPIRED',
] as const

export const taskStatusSchema = z.enum(TASK_STATUS_VALUES)

export type ReviewSource =
  | 'LEARN'
  | 'REVIEW'
  | 'QUIZ'
  | 'EXAM'
  | 'NOTEBOOK'
  | 'CHALLENGE'

export const REVIEW_SOURCE_VALUES = [
  'LEARN',
  'REVIEW',
  'QUIZ',
  'EXAM',
  'NOTEBOOK',
  'CHALLENGE',
] as const

export const reviewSourceSchema = z.enum(REVIEW_SOURCE_VALUES)

export type AiCapability =
  | 'WORD_EXPLAIN'
  | 'WRITING_REVIEW'
  | 'SPEAKING_SCORE'
  | 'PRONUNCIATION_ANALYZE'
  | 'READING_EXPLAIN'
  | 'GRAMMAR_EXPLAIN'
  | 'PLAN_GENERATE'
  | 'PLAN_ADJUST'
  | 'DAILY_DIAGNOSIS'
  | 'TUTOR_CHAT'
  | 'TRANSLATE'
  | 'LISTENING_ANALYZE'
  | 'MISTAKE_CLASSIFY'
  | 'READING_QUIZ_GENERATE'
  | 'WORD_SCENARIO'
  | 'RECOMMEND'
  | 'EXAM_ESSAY_SCORE'
  | 'CET_ADVICE'

export const AI_CAPABILITY_VALUES = [
  'WORD_EXPLAIN',
  'WRITING_REVIEW',
  'SPEAKING_SCORE',
  'PRONUNCIATION_ANALYZE',
  'READING_EXPLAIN',
  'GRAMMAR_EXPLAIN',
  'PLAN_GENERATE',
  'PLAN_ADJUST',
  'DAILY_DIAGNOSIS',
  'TUTOR_CHAT',
  'TRANSLATE',
  'LISTENING_ANALYZE',
  'MISTAKE_CLASSIFY',
  'READING_QUIZ_GENERATE',
  'WORD_SCENARIO',
  'RECOMMEND',
  'EXAM_ESSAY_SCORE',
  'CET_ADVICE',
] as const

export const aiCapabilitySchema = z.enum(AI_CAPABILITY_VALUES)

export type AiCallStatus =
  | 'SUCCESS'
  | 'ERROR'
  | 'TIMEOUT'
  | 'DEGRADED'
  | 'RATE_LIMITED'
  | 'CONTENT_BLOCKED'

export const AI_CALL_STATUS_VALUES = [
  'SUCCESS',
  'ERROR',
  'TIMEOUT',
  'DEGRADED',
  'RATE_LIMITED',
  'CONTENT_BLOCKED',
] as const

export const aiCallStatusSchema = z.enum(AI_CALL_STATUS_VALUES)

export type PromptStatus =
  | 'DRAFT'
  | 'ACTIVE'
  | 'ARCHIVED'

export const PROMPT_STATUS_VALUES = [
  'DRAFT',
  'ACTIVE',
  'ARCHIVED',
] as const

export const promptStatusSchema = z.enum(PROMPT_STATUS_VALUES)

export type MessageRole =
  | 'USER'
  | 'ASSISTANT'
  | 'SYSTEM'

export const MESSAGE_ROLE_VALUES = [
  'USER',
  'ASSISTANT',
  'SYSTEM',
] as const

export const messageRoleSchema = z.enum(MESSAGE_ROLE_VALUES)

export type ConversationType =
  | 'TUTOR'
  | 'SPEAKING_PARTNER'
  | 'WORD_EXPLAINER'
  | 'GRAMMAR_EXPLAINER'
  | 'READING_EXPLAINER'

export const CONVERSATION_TYPE_VALUES = [
  'TUTOR',
  'SPEAKING_PARTNER',
  'WORD_EXPLAINER',
  'GRAMMAR_EXPLAINER',
  'READING_EXPLAINER',
] as const

export const conversationTypeSchema = z.enum(CONVERSATION_TYPE_VALUES)

export type SpeakingStatus =
  | 'ACTIVE'
  | 'COMPLETED'
  | 'ABANDONED'

export const SPEAKING_STATUS_VALUES = [
  'ACTIVE',
  'COMPLETED',
  'ABANDONED',
] as const

export const speakingStatusSchema = z.enum(SPEAKING_STATUS_VALUES)

export type Speaker =
  | 'USER'
  | 'AI'

export const SPEAKER_VALUES = [
  'USER',
  'AI',
] as const

export const speakerSchema = z.enum(SPEAKER_VALUES)

export type SubmissionStatus =
  | 'DRAFT'
  | 'SUBMITTED'
  | 'GRADING'
  | 'SCORED'

export const SUBMISSION_STATUS_VALUES = [
  'DRAFT',
  'SUBMITTED',
  'GRADING',
  'SCORED',
] as const

export const submissionStatusSchema = z.enum(SUBMISSION_STATUS_VALUES)

export type NotificationType =
  | 'STUDY_REMINDER'
  | 'REVIEW_REMINDER'
  | 'PLAN_REMINDER'
  | 'EXAM_REMINDER'
  | 'STREAK_REMINDER'
  | 'ACHIEVEMENT'
  | 'SYSTEM'

export const NOTIFICATION_TYPE_VALUES = [
  'STUDY_REMINDER',
  'REVIEW_REMINDER',
  'PLAN_REMINDER',
  'EXAM_REMINDER',
  'STREAK_REMINDER',
  'ACHIEVEMENT',
  'SYSTEM',
] as const

export const notificationTypeSchema = z.enum(NOTIFICATION_TYPE_VALUES)

export type Channel =
  | 'IN_APP'
  | 'EMAIL'
  | 'PUSH'

export const CHANNEL_VALUES = [
  'IN_APP',
  'EMAIL',
  'PUSH',
] as const

export const channelSchema = z.enum(CHANNEL_VALUES)

export type AchievementCategory =
  | 'STREAK'
  | 'VOCABULARY'
  | 'STUDY_TIME'
  | 'EXAM'
  | 'WRITING'
  | 'SPEAKING'
  | 'LISTENING'
  | 'READING'
  | 'SPECIAL'

export const ACHIEVEMENT_CATEGORY_VALUES = [
  'STREAK',
  'VOCABULARY',
  'STUDY_TIME',
  'EXAM',
  'WRITING',
  'SPEAKING',
  'LISTENING',
  'READING',
  'SPECIAL',
] as const

export const achievementCategorySchema = z.enum(ACHIEVEMENT_CATEGORY_VALUES)

export type SubscriptionPlan =
  | 'FREE'
  | 'PRO'
  | 'PREMIUM'

export const SUBSCRIPTION_PLAN_VALUES = [
  'FREE',
  'PRO',
  'PREMIUM',
] as const

export const subscriptionPlanSchema = z.enum(SUBSCRIPTION_PLAN_VALUES)

export type SubscriptionStatus =
  | 'TRIALING'
  | 'ACTIVE'
  | 'EXPIRED'
  | 'CANCELLED'

export const SUBSCRIPTION_STATUS_VALUES = [
  'TRIALING',
  'ACTIVE',
  'EXPIRED',
  'CANCELLED',
] as const

export const subscriptionStatusSchema = z.enum(SUBSCRIPTION_STATUS_VALUES)

/** 全部枚举取值（供 Admin 下拉 / 校验 / 文档使用）。 */
export const ALL_ENUMS = {
  Role: ROLE_VALUES,
  UserStatus: USER_STATUS_VALUES,
  CEFRLevel: CEFRLEVEL_VALUES,
  MasteryStage: MASTERY_STAGE_VALUES,
  GoalType: GOAL_TYPE_VALUES,
  GoalStatus: GOAL_STATUS_VALUES,
  ExamType: EXAM_TYPE_VALUES,
  Difficulty: DIFFICULTY_VALUES,
  QuestionType: QUESTION_TYPE_VALUES,
  ExamSection: EXAM_SECTION_VALUES,
  AttemptStatus: ATTEMPT_STATUS_VALUES,
  PublishStatus: PUBLISH_STATUS_VALUES,
  PlanSource: PLAN_SOURCE_VALUES,
  PlanStatus: PLAN_STATUS_VALUES,
  TaskType: TASK_TYPE_VALUES,
  TaskStatus: TASK_STATUS_VALUES,
  ReviewSource: REVIEW_SOURCE_VALUES,
  AiCapability: AI_CAPABILITY_VALUES,
  AiCallStatus: AI_CALL_STATUS_VALUES,
  PromptStatus: PROMPT_STATUS_VALUES,
  MessageRole: MESSAGE_ROLE_VALUES,
  ConversationType: CONVERSATION_TYPE_VALUES,
  SpeakingStatus: SPEAKING_STATUS_VALUES,
  Speaker: SPEAKER_VALUES,
  SubmissionStatus: SUBMISSION_STATUS_VALUES,
  NotificationType: NOTIFICATION_TYPE_VALUES,
  Channel: CHANNEL_VALUES,
  AchievementCategory: ACHIEVEMENT_CATEGORY_VALUES,
  SubscriptionPlan: SUBSCRIPTION_PLAN_VALUES,
  SubscriptionStatus: SUBSCRIPTION_STATUS_VALUES,
} as const

export type EnumName = keyof typeof ALL_ENUMS
