/**
 * `npm run prisma:sqlite` —— 由 `prisma/schema.prisma` 机械生成 SQLite 逃生版
 * `prisma/schema.sqlite.prisma`（架构 §2.6.3，禁止手工修改生成物）。
 *
 * 转换规则：
 *  1. datasource → provider "sqlite"，url = env("DATABASE_URL_SQLITE")
 *  2. 删除全部 enum 块，字段中的枚举类型改写为 String（追加 `// was enum: X`）
 *  3. Json → String（业务层经 lib/utils/safe-json.ts 适配）
 *  4. 移除 `@db.*` 原生类型注解
 *  5. 枚举默认值加引号：@default(USER) → @default("USER")
 */
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SRC = path.join(ROOT, 'prisma', 'schema.prisma')
const OUT = path.join(ROOT, 'prisma', 'schema.sqlite.prisma')

const schema = fs.readFileSync(SRC, 'utf8')

// ---- 1. 收集 enum 名与取值 -------------------------------------------------
const enumNames = new Set<string>()
const enumValues = new Map<string, string[]>()
const enumBlockRe = /^enum\s+([A-Za-z0-9_]+)\s*\{([\s\S]*?)^\}/gm
for (const match of schema.matchAll(enumBlockRe)) {
  const name = match[1]
  if (!name) continue
  enumNames.add(name)
  const values: string[] = []
  for (const line of (match[2] ?? '').split('\n')) {
    const v = /^([A-Za-z0-9_]+)/.exec(line.trim())?.[1]
    if (v) values.push(v)
  }
  enumValues.set(name, values)
}

let out = schema

// ---- 2. datasource --------------------------------------------------------
out = out.replace(/provider\s*=\s*"postgresql"/, 'provider = "sqlite"')
out = out.replace(/url\s*=\s*env\("DATABASE_URL"\)/, 'url = env("DATABASE_URL_SQLITE")')

// ---- 3. 删除 enum 块 ------------------------------------------------------
out = out.replace(/^\/\/\/.*$/gm, '') // 先去掉三斜杠注释（避免 enum 块残留孤立注释）
out = out.replace(/^enum\s+[A-Za-z0-9_]+\s*\{[\s\S]*?^\}\n?/gm, '')

// ---- 4. 字段类型与注解 ----------------------------------------------------
const lines = out.split('\n')
const rewritten: string[] = []
for (const raw of lines) {
  let line = raw
  // 4.1 移除 @db.* 注解
  line = line.replace(/\s+@db\.\w+/, '')
  // 4.2 Json → String（含可选）
  if (/\bJson\b/.test(line)) {
    line = line.replace(/\bJson(\[\])?/g, 'String')
    if (!line.includes('was Json')) line = `${line} // was Json`
  }
  // 4.3 enum 类型 → String + 默认值加引号
  for (const name of enumNames) {
    if (new RegExp(`\\b${name}\\??\\b`).test(line)) {
      const isFieldLine = /\w+\s+(?:[A-Za-z0-9_]+)(\[\])?\??\s+@?[=A-Za-z(]*/.test(line) && !line.includes('model ')
      if (isFieldLine) {
        line = line.replace(new RegExp(`\\b${name}(\\[\\])?(\\?)?`), 'String$2')
        line = `${line} // was enum: ${name}`
        for (const value of enumValues.get(name) ?? []) {
          line = line.replace(
            new RegExp(`@default\\(${value}\\)`),
            `@default("${value}")`,
          )
        }
      }
    }
  }
  rewritten.push(line)
}
out = rewritten.join('\n')

// ---- 5. 压缩多余空行 ------------------------------------------------------
out = out.replace(/\n{3,}/g, '\n\n').replace(/^\s*\n/gm, '\n').trimStart()

fs.writeFileSync(
  OUT,
  `// ⚠️ AUTO-GENERATED by \`npm run prisma:sqlite\` — DO NOT EDIT（架构 §2.6.3）\n\n${out}\n`,
  'utf8',
)
process.stdout.write(
  `[gen-sqlite-schema] wrote ${path.relative(ROOT, OUT)} (enums: ${enumNames.size} → String, Json → String)\n`,
)
