/**
 * `npm run enums:sync` —— 从 `prisma/schema.prisma` 生成 `src/types/enums.ts`
 * （架构 §2.5.1 / §10.11：Prisma enum ↔ TS ↔ Zod 三方同源，生成物禁止手改）。
 */
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SCHEMA_PATH = path.join(ROOT, 'prisma', 'schema.prisma')
const OUT_PATH = path.join(ROOT, 'src', 'types', 'enums.ts')

interface EnumDef {
  name: string
  values: string[]
  comment: string
}

function parseEnums(schema: string): EnumDef[] {
  const enums: EnumDef[] = []
  const blockRegex = /^enum\s+([A-Za-z0-9_]+)\s*\{([\s\S]*?)^\}/gm
  for (const match of schema.matchAll(blockRegex)) {
    const name = match[1]
    if (!name) continue
    const body = match[2] ?? ''
    const lines = body.split('\n')
    const values: string[] = []
    let comment = ''
    for (const rawLine of lines) {
      const line = rawLine.trim()
      if (line.startsWith('///')) {
        comment = line.replace(/^\/\/\/\s*/, '')
        continue
      }
      if (line.startsWith('//') || line === '') continue
      const valueMatch = /^([A-Za-z0-9_]+)/.exec(line)
      if (valueMatch?.[1]) values.push(valueMatch[1])
    }
    enums.push({ name, values, comment })
  }
  return enums
}

const toConst = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()

function render(enums: EnumDef[]): string {
  const header = `/**
 * ★ AUTO-GENERATED by \`npm run enums:sync\` — DO NOT EDIT（架构 §10.11）
 * 来源：prisma/schema.prisma（${enums.length} 个 enum）。
 * 修改枚举请改 schema 后重新运行 \`npm run enums:sync\`。
 */
import { z } from 'zod'

`

  const blocks = enums.map((e) => {
    const constName = `${toConst(e.name)}_VALUES`
    const valuesList = e.values.map((v) => `  | '${v}'`).join('\n')
    const arrayBody = e.values.map((v) => `  '${v}',`).join('\n')
    const schemaName = `${e.name.charAt(0).toLowerCase()}${e.name.slice(1)}Schema`
    const doc = e.comment ? `/** ${e.comment} */\n` : ''
    return `${doc}export type ${e.name} =
${valuesList}

export const ${constName} = [
${arrayBody}
] as const

export const ${schemaName} = z.enum(${constName})
`
  })

  const maps = enums
    .map((e) => `  ${e.name}: ${toConst(e.name)}_VALUES,`)
    .join('\n')

  const footer = `
/** 全部枚举取值（供 Admin 下拉 / 校验 / 文档使用）。 */
export const ALL_ENUMS = {
${maps}
} as const

export type EnumName = keyof typeof ALL_ENUMS
`

  return `${header}${blocks.join('\n')}${footer}`
}

const schema = fs.readFileSync(SCHEMA_PATH, 'utf8')
const enums = parseEnums(schema)
if (enums.length === 0) {
  process.stderr.write('[enums:sync] no enum parsed — aborting\n')
  process.exit(1)
}
fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true })
fs.writeFileSync(OUT_PATH, render(enums), 'utf8')
process.stdout.write(`[enums:sync] wrote ${enums.length} enums → ${path.relative(ROOT, OUT_PATH)}\n`)
